import "./globals.css";
import { AuthProvider } from "../Components/Layout/AuthContext";
import React, { useContext } from "react";
import { AppProvider } from "../Components/AppContext";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Import Roboto font directly in RootLayout component
const roboto = {
  fontFamily: "'Roboto', sans-serif",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={roboto}>

     
      <main className="mx-auto">{children}</main>
     
      
           
       
       
         
        
      </body>
    </html>
  );
}
